In [3]:
import pandas as pd

In [4]:
coffee = pd.read_csv("./warmup-data/coffee.csv")
results = pd.read_csv("./data/results.csv")
bios = pd.read_csv("./data/bios.csv")

coffee.head()
# results.head()
# bios.head()

Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [5]:
coffee.loc[[0,1,2], ["Day"]]
coffee.loc[[0,1,2]]

Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [6]:
coffee.loc[0:2, ["Day","Units Sold"]]

Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30

In [7]:
coffee.loc[:, ["Day","Units Sold"]]

Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [8]:
# coffee.index = coffee["Day"]
# coffee.loc["Tuesday":"Thursday", ["Day","Units Sold"]]
coffee.iloc[0:5, [0,2]] # only using with index


Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [9]:
coffee.loc[1, "Units Sold"] = 10
coffee.head()

Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [10]:
# coffee.loc[1:3, "Units Sold"] = 10
# coffee.head()

In [11]:
coffee.at[0, "Units Sold"]


np.int64(25)

In [12]:
coffee["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [13]:
# coffee.sort_values("Units Sold")
# coffee.sort_values("Units Sold", ascending=False) # Giảm dần
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0,1]) # Units Sold false, Coffee Type true

Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [14]:
bios.head()

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg   died_date  
0               Gironde          FRA  France        NaN        NaN  1960-10-02  
1              Yvelines          FRA  France      183.0       76.0         NaN  
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17  
3                 Paris          FRA  France      168.0       64.0  1978-03-20  
4               England          GBR  France        NaN        NaN  1930-07-25

In [15]:
bios.loc[bios["height_cm"] > 215]

athlete_id                   name   born_date               born_city  \
5089          5108     Viktor Pankrashkin  1957-06-19         Moskva (Moscow)   
5583          5606   Paulinho Villas Boas  1963-01-26               São Paulo   
5673          5696         Gunther Behnke  1963-01-19              Leverkusen   
5716          5739               Uwe Blab  1962-03-26        München (Munich)   
5781          5804         Tommy Burleson  1952-02-24               Crossnore   
5796          5819          Andy Campbell  1956-07-21               Melbourne   
6223          6250            Lars Hansen  1954-09-27  København (Copenhagen)   
6270          6298            Hu Zhangbao  1963-04-05                     NaN   
6409          6440       Sergey Kovalenko  1947-08-11                     NaN   
6420          6451          Jānis Krūmiņš  1930-01-30                   Cēsis   
6504          6537            Luc Longley  1969-01-19               Melbourne   
6722          6755       Shaquille O'Neal  1972-03-06                  Newark   
6937          6972         David Robinson  1965-08-06                Key West   
6978          7013        Arvydas Sabonis  1964-12-19                  Kaunas   
7074          7111         Paulo da Silva  1963-07-21               São Paulo   
7188          7226     Vladimir Tkachenko  1957-09-20               Golovinka   
7281          7320       Stojko Vranković  1964-01-22                   Drniš   
7376          7416    Eurelijus Žukauskas  1973-08-22                Klaipėda   
52608        52983        Aleksey Kazakov  1976-03-18      Naberezhnye Chelny   
82100        82753          Frédéric Weis  1977-06-22              Thionville   
89070        89782               Yao Ming  1980-09-12          Xuhui District   
89075        89787         Roberto Dueñas  1975-11-01                  Madrid   
107408      108533       Peter John Ramos  1985-05-23                 Fajardo   
112312      113568           Stanko Barać  1986-08-13                  Mostar   
112332      113588    Andreas Glyniadakis  1981-08-26                  Chania   
112337      113593          Hamed Haddadi  1985-05-19                   Ahvaz   
118663      120400         Timofey Mozgov  1986-07-16                     NaN   
118676      120415        Dmitry Musersky  1988-10-29                Makiïvka   
120266      122147           Zhang Zhaoxu  1987-11-18                 Binzhou   
121694      123709            Salah Mejri  1986-06-15                Jendouba   
123850      126093         Tyson Chandler  1982-10-02                 Hanford   
130460      133147               Li Muhao  1992-06-02                 Guiyang   
130461      133148                Zhou Qi  1996-01-16                Xinxiang   
138671      142084          Ondřej Balvín  1992-09-20          Ústí nad Labem   
139365      142836         Moustapha Fall  1992-02-23                   Paris   

                            born_region born_country  \
5089                             Moskva          RUS   
5583                          São Paulo          BRA   
5673                Nordrhein-Westfalen          GER   
5716                             Bayern          GER   
5781                     North Carolina          USA   
5796                           Victoria          AUS   
6223                        Hovedstaden          DEN   
6270                                NaN          NaN   
6409                                NaN          NaN   
6420                        Cēsu novads          LAT   
6504                           Victoria          AUS   
6722                         New Jersey          USA   
6937                            Florida          USA   
6978                             Kaunas          LTU   
7074                          São Paulo          BRA   
7188                     Krasnodar Kray          RUS   
7281          Šibensko-kninska županija          CRO   
7376                           Klaipėda          LTU   
52608              Respubli

In [16]:
bios.loc[bios["height_cm"] > 215, ["name", "height_cm"]]
bios[bios["height_cm"] > 216][["name", "height_cm"]]

name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112337          Hamed Haddadi      218.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
139365         Moustapha Fall      218.0

In [17]:
bios[(bios["height_cm"] > 215) & (bios["born_country"] == 'USA')]

athlete_id              name   born_date  born_city     born_region  \
5781          5804    Tommy Burleson  1952-02-24  Crossnore  North Carolina   
6722          6755  Shaquille O'Neal  1972-03-06     Newark      New Jersey   
6937          6972    David Robinson  1965-08-06   Key West         Florida   
123850      126093    Tyson Chandler  1982-10-02    Hanford      California   

       born_country            NOC  height_cm  weight_kg died_date  
5781            USA  United States      223.0      102.0       NaN  
6722            USA  United States      216.0      137.0       NaN  
6937            USA  United States      216.0      107.0       NaN  
123850          USA  United States      216.0      107.0       NaN

In [18]:
bios[bios["name"].str.contains("Keith")]

athlete_id                  name   born_date         born_city  \
1897          1907          Keith Hanlon  1966-09-01               NaN   
3505          3517         Keith Wallace  1961-03-29           Preston   
6228          6255         Keith Hartley  1940-10-15         Vancouver   
8898          8946           Keith Mwila  1966-01-01               NaN   
12053        12118          Keith Hervey  1898-11-03            Fulham   
...            ...                   ...         ...               ...   
109900      111105     Keith Cumberpatch  1927-08-25      Christchurch   
115973      117348       Keith Sanderson  1975-02-02          Plymouth   
117676      119195          Duncan Keith  1983-07-16          Winnipeg   
122121      124176        Keith Ferguson  1979-09-07              Sale   
127310      129749  Tracy Keith-Matchitt  1990-03-30  Palmerston North   

              born_region born_country            NOC  height_cm  weight_kg  \
1897                  NaN          NaN        Ireland        NaN        NaN   
3505              England          GBR  Great Britain      165.0       51.0   
6228     British Columbia          CAN         Canada      200.0       85.0   
8898                  NaN          NaN         Zambia        NaN        NaN   
12053             England          GBR  Great Britain        NaN        NaN   
...                   ...          ...            ...        ...        ...   
109900         Canterbury          NZL    New Zealand        NaN        NaN   
115973      Massachusetts          USA  United States      183.0       95.0   
117676           Manitoba          CAN         Canada      185.0       88.0   
122121           Victoria          AUS      Australia      176.0       78.0   
127310  Manawatu-Wanganui          NZL   Cook Islands      167.0       60.0   

         died_date  
1897           NaN  
3505    1999-12-31  
6228           NaN  
8898    1993-01-09  
12053   1973-02-22  
...            ...  
109900  2013-11-15  
115973         NaN  
117676         NaN  
122121         NaN  
127310         NaN  

[70 rows x 10 columns]

In [19]:
bios[bios["name"].str.contains("keith|patrick", case=False)]

athlete_id               name   born_date              born_city  \
6                7      Patrick Chila  1969-11-27            Ris-Orangis   
119            120   Patrick Wheatley  1899-01-20                Vryheid   
319            320  Patrick De Koning  1961-04-23            Dendermonde   
1897          1907       Keith Hanlon  1966-09-01                    NaN   
2115          2125       Patrick Jopp  1962-01-08                    NaN   
...            ...                ...         ...                    ...   
143975      147633  Patrick Chinyemba  2001-01-03                    NaN   
144172      147850      Patrick Jakob  1996-10-17  Sankt Johann in Tirol   
144547      148239  Patrick Galbraith  1986-03-11              Haderslev   
144565      148257    Patrick Russell  1993-01-04               Gentofte   
145435      149158  Patrick Gasienica  1998-11-28                McHenry   

            born_region born_country            NOC  height_cm  weight_kg  \
6               Essonne          FRA         France      180.0       73.0   
119       KwaZulu-Natal          RSA  Great Britain        NaN        NaN   
319     Oost-Vlaanderen          BEL        Belgium      178.0       92.0   
1897                NaN          NaN        Ireland        NaN        NaN   
2115                NaN          NaN    Switzerland      176.0       67.0   
...                 ...          ...            ...        ...        ...   
143975              NaN          NaN         Zambia        NaN        NaN   
144172            Tirol          AUT        Austria        NaN        NaN   
144547       Syddanmark          DEN        Denmark        NaN        NaN   
144565      Hovedstaden          DEN        Denmark      186.0       93.0   
145435         Illinois          USA  United States        NaN        NaN   

         died_date  
6              NaN  
119     1967-11-05  
319            NaN  
1897           NaN  
2115           NaN  
...            ...  
143975         NaN  
144172         NaN  
144547         NaN  
144565         NaN  
145435  2023-06-12  

[303 rows x 10 columns]

In [20]:
bios[(bios["born_country"].isin(["USA", "FRA", "GBR"])) & (bios["name"].str.startswith("Keith"))]

athlete_id                name   born_date             born_city  \
3505          3517       Keith Wallace  1961-03-29               Preston   
12053        12118        Keith Hervey  1898-11-03                Fulham   
14577        14674      Keith Harrison  1933-03-28            Birmingham   
16166        16281      Keith Reynolds  1963-12-25              Solihull   
18734        18862      Keith Sinclair  1945-06-26            Sunderland   
29897        30123       Keith Langley  1961-06-03             Aldershot   
34011        34275        Keith Remfry  1947-11-17                Ealing   
46885        47234        Keith Collin  1937-01-18            Marylebone   
50929        51288        Keith Carter  1924-08-30                 Akron   
51185        51544       Keith Russell  1948-01-15                  Mesa   
52913        53288      Keith Erickson  1944-04-19         San Francisco   
55317        55712        Keith Boxell  1958-05-06               Clapham   
57818        58226        Keith Peache  1947-08-10              Lewisham   
61748        62202       Keith Grogono  1912-11-04             Stratford   
62620        63086         Keith Musto  1936-01-12              Rochford   
62678        63144        Keith Notary  1960-01-22        Merritt Island   
68324        68841         Keith Angus  1943-04-05             Sheffield   
68472        68989        Keith Cullen  1972-06-13                Ilford   
68997        69514         Keith Stock  1957-03-18              Woolwich   
77550        78141       Keith Brantly  1962-05-23  Scott Air Force Base   
84097        84766  Keith Christiansen  1944-07-14   International Falls   
94646        95413         Keith Meyer  1938-06-20                Geneva   
95267        96037        Keith Oliver  1947-10-27             Liverpool   
96452        97229  Keith Schellenberg  1929-03-13         Middlesbrough   
97499        98286       Keith Tkachuk  1972-03-28               Melrose   
98068        98860       Keith Wegeman  1929-08-28                Denver   
99921       100722        Keith Carney  1970-02-03            Providence   
115973      117348     Keith Sanderson  1975-02-02              Plymouth   

          born_region born_country            NOC  height_cm  weight_kg  \
3505          England          GBR  Great Britain      165.0       51.0   
12053         England          GBR  Great Britain        NaN        NaN   
14577         England          GBR  Great Britain        NaN        NaN   
16166         England          GBR  Great Britain      173.0       68.0   
18734         England          GBR  Great Britain      190.0       79.0   
29897         England          GBR  Great Britain      173.0       70.0   
34011         England          GBR  Great Britain      193.0      114.0   
46885         England          GBR  Great Britain      168.0       63.0   
50929            Ohio          USA  United States        NaN        NaN   
51185         Arizona          USA  United States      188.0       73.0   
52913      California          USA  United States      196.0       86.0   
55317         England          GBR  Great Britain      170.0       87.0   
57818         England          GBR  Great Britain      180.0       98.0   
61748         England          GBR  Great Britain        NaN        NaN   
62620         England          GBR  Great Britain      174.0       72.0   
62678         Florida          USA  United States      170.0       66.0   
68324         England          GBR  Great Britain      170.0       59.0   
68472         England          GBR  Great Britain      177.0       61.0   
68997         England          GBR  Great Britain      176.0       73.0   
77550        Illinois          USA  United States      180.0       64.0   
84097       Minnesota          USA  United States      165.0       69.0   
94646        Illinois          USA  United States        NaN        NaN   
95267         England          GBR  Great Britain      172.0       68.0   
964

In [21]:
bios.query('born_country == "USA"')

athlete_id               name   born_date         born_city  \
54              55      Monique Javer  1967-07-22        Burlingame   
960            964   Xóchitl Escobedo  1968-09-17       West Covina   
961            965  Angélica Gavaldón  1973-10-03         El Centro   
1231          1238     Bert Schneider  1897-07-01         Cleveland   
1345          1352         Laura Berg  1975-01-06  Santa Fe Springs   
...            ...                ...         ...               ...   
145445      149168     Kristen Santos  1994-11-02         Fairfield   
145446      149169   Corinne Stoddard  2001-08-15           Seattle   
145454      149180      Anna Hoffmann  2000-03-28           Madison   
145457      149183     Alix Wilkinson  2000-08-02     Mammoth Lakes   
145468      149195  Justin Abdelkader  1987-02-25          Muskegon   

        born_region born_country            NOC  height_cm  weight_kg  \
54       California          USA  Great Britain      177.0       64.0   
960      California          USA         Mexico      170.0       60.0   
961      California          USA         Mexico      160.0       54.0   
1231           Ohio          USA         Canada        NaN        NaN   
1345     California          USA  United States      168.0       61.0   
...             ...          ...            ...        ...        ...   
145445  Connecticut          USA  United States        NaN        NaN   
145446   Washington          USA  United States        NaN        NaN   
145454    Wisconsin          USA  United States        NaN        NaN   
145457   California          USA  United States        NaN        NaN   
145468     Michigan          USA  United States      187.0       97.0   

         died_date  
54             NaN  
960            NaN  
961            NaN  
1231    1986-02-20  
1345           NaN  
...            ...  
145445         NaN  
145446         NaN  
145454         NaN  
145457         NaN  
145468         NaN  

[9641 rows x 10 columns]

In [22]:
import numpy as np

# Tạo một mảng NumPy 2x2
array = np.array([[1, 2], [3, 4]])

# Phép toán cộng với một số
result = array + 10

print(result)

[[11 12]
 [13 14]]


In [23]:
import numpy as np

# Tạo một mảng 1 chiều từ 0 đến 9
array = np.arange(10)

# Phép toán cộng, trừ, nhân, chia với một số
add_result = array + 5
subtract_result = array - 2
multiply_result = array * 3
divide_result = array / 2

print("Mảng ban đầu:", array)
print("Cộng 5:", add_result)
print("Trừ 2:", subtract_result)
print("Nhân 3:", multiply_result)
print("Chia 2:", divide_result)


Mảng ban đầu: [0 1 2 3 4 5 6 7 8 9]
Cộng 5: [ 5  6  7  8  9 10 11 12 13 14]
Trừ 2: [-2 -1  0  1  2  3  4  5  6  7]
Nhân 3: [ 0  3  6  9 12 15 18 21 24 27]
Chia 2: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [24]:
import numpy as np

# Tạo một mảng 3x3
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Tạo một mảng 1 chiều
vector = np.array([1, 0, -1])

# Broadcasting: cộng vector vào từng hàng của ma trận
result = matrix + vector

print("Ma trận ban đầu:\n", matrix)
print("Vector:", vector)
print("Kết quả của broadcasting:\n", result)


Ma trận ban đầu:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector: [ 1  0 -1]
Kết quả của broadcasting:
 [[2 2 2]
 [5 5 5]
 [8 8 8]]


In [25]:
import numpy as np

# Tạo một mảng 3 chiều (2x2x3)
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Truy cập các phần tử trong mảng 3 chiều
element = array_3d[1, 0, 2]  # Truy cập phần tử 9
sub_array = array_3d[:, 1, :]  # Lấy các hàng thứ hai của từng mảng con


print("mảng array_3d:", array_3d)
print("Phần tử tại [1, 0, 2]:", element)
print("Mảng con chứa hàng thứ hai của từng mảng con:\n", sub_array)


mảng array_3d: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Phần tử tại [1, 0, 2]: 9
Mảng con chứa hàng thứ hai của từng mảng con:
 [[ 4  5  6]
 [10 11 12]]


In [26]:
import numpy as np

# Tạo một mảng ngẫu nhiên 10 phần tử
random_array = np.random.randn(10)

# Tính các chỉ số thống kê
mean = np.mean(random_array)
std_dev = np.std(random_array)
variance = np.var(random_array)

print("Mảng ngẫu nhiên:", random_array)
print("Trung bình:", mean)
print("Độ lệch chuẩn:", std_dev)
print("Phương sai:", variance)


Mảng ngẫu nhiên: [-0.68574651  0.38657019  1.54171059 -0.26941565 -0.41028045 -1.57981862
 -1.50175267 -1.16891671  0.88830897  1.71257177]
Trung bình: -0.1086769075681457
Độ lệch chuẩn: 1.1383678496738276
Phương sai: 1.2958813611710143


In [27]:
import numpy as np

# Tạo một mảng từ 0 đến 15
array = np.arange(16)

# Lọc các phần tử lớn hơn 8
filtered_array = array[array > 8]

print("Mảng ban đầu:", array)
print("Các phần tử lớn hơn 8:", filtered_array)


Mảng ban đầu: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Các phần tử lớn hơn 8: [ 9 10 11 12 13 14 15]


In [28]:
import numpy as np

# Tạo một mảng 5x5
matrix = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])

# Lấy các phần tử từ hàng 2 đến hàng 4 và cột 1 đến cột 3
sub_matrix = matrix[1:4, 0:3]

print("Ma trận ban đầu:\n", matrix)
print("Phần tử từ hàng 2 đến hàng 4 và cột 1 đến cột 3:\n", sub_matrix)


Ma trận ban đầu:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Phần tử từ hàng 2 đến hàng 4 và cột 1 đến cột 3:
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [29]:
import numpy as np

# Tạo một mảng 1 chiều từ 1 đến 12
array = np.arange(1, 13)

# Reshape thành ma trận 3x4
reshaped_array = array.reshape(3, 4)

print("Mảng ban đầu:", array)
print("Mảng sau khi reshape thành 3x4:\n", reshaped_array)


Mảng ban đầu: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Mảng sau khi reshape thành 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
import numpy as np

# Tạo mảng toàn giá trị 0 kích thước 3x3
zeros_array = np.zeros((3, 3))

# Tạo mảng toàn giá trị 1 kích thước 2x4
ones_array = np.ones((2, 4))

# Tạo ma trận đơn vị 4x4
identity_matrix = np.eye(4)

print("Mảng toàn 0:\n", zeros_array)
print("Mảng toàn 1:\n", ones_array)
print("Ma trận đơn vị:\n", identity_matrix)


Mảng toàn 0:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Mảng toàn 1:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ma trận đơn vị:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
import numpy as np

# Tạo một mảng ngẫu nhiên với giá trị từ 0 đến 1 (phân phối đều)
uniform_random = np.random.rand(3, 3)

# Tạo một mảng ngẫu nhiên từ phân phối chuẩn
normal_random = np.random.randn(3, 3)

print("Mảng ngẫu nhiên phân phối đều:\n", uniform_random)
print("Mảng ngẫu nhiên phân phối chuẩn:\n", normal_random)


Mảng ngẫu nhiên phân phối đều:
 [[0.32612716 0.69710161 0.14560505]
 [0.20296601 0.96567128 0.73784528]
 [0.17394379 0.23731557 0.39286856]]
Mảng ngẫu nhiên phân phối chuẩn:
 [[-1.05613534 -0.08693246 -0.67987168]
 [-1.32825239 -0.8470814   0.00605503]
 [-0.67968568  0.93431593  0.77290341]]


In [32]:
coffee_new = coffee.copy()
coffee_new["price"] = 4.99
coffee_new.head()

Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          10   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [33]:
coffee

Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [34]:
coffee_new["new_price"] = np.where(coffee["Coffee Type"] == "Espresso", 3.99, 5.99)
coffee_new

Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          10   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [35]:
# coffee.drop(columns=["price"], inplace=True)
coffee

Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [36]:
coffee["new_price"] = np.where(coffee["Coffee Type"] == "Espresso", 3.99, 5.99)
coffee

Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          10       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [37]:
coffee["revenue"] = coffee["new_price"] * coffee["Units Sold"]
coffee

Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          10       5.99    59.90
2     Tuesday    Espresso          30       3.99   119.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

In [38]:
# coffee.rename(columns={"new_price": "price"}, implace=True)
coffee = coffee.rename(columns={"new_price": "price"})

In [39]:
coffee

Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          10   5.99    59.90
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [40]:
bios.head()

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg   died_date  
0               Gironde          FRA  France        NaN        NaN  1960-10-02  
1              Yvelines          FRA  France      183.0       76.0         NaN  
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17  
3                 Paris          FRA  France      168.0       64.0  1978-03-20  
4               England          GBR  France        NaN        NaN  1930-07-25

In [41]:
bios_new = bios.copy()
bios_new["first_name"] = bios_new["name"].str.split(" ").str[0]
bios_new

athlete_id                   name   born_date        born_city  \
0                1  Jean-François Blanchy  1886-12-12         Bordeaux   
1                2         Arnaud Boetsch  1969-04-01           Meulan   
2                3           Jean Borotra  1898-08-13         Biarritz   
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe   
4                5           Albert Canet  1878-04-17       Wandsworth   
...            ...                    ...         ...              ...   
145495      149222      Polina Luchnikova  2002-01-30            Serov   
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)   
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas   
145498      149225         André Foussard  1899-05-19            Niort   
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill   

                 born_region born_country        NOC  height_cm  weight_kg  \
0                    Gironde          FRA     France        NaN        NaN   
1                   Yvelines          FRA     France      183.0       76.0   
2       Pyrénées-Atlantiques          FRA     France      183.0       76.0   
3                      Paris          FRA     France      168.0       64.0   
4                    England          GBR     France        NaN        NaN   
...                      ...          ...        ...        ...        ...   
145495            Sverdlovsk          RUS        ROC      167.0       61.0   
145496                Moskva          RUS        ROC      168.0       65.0   
145497           Arkhangelsk          RUS        ROC      163.0       55.0   
145498           Deux-Sèvres          FRA     France      166.0        NaN   
145499       New South Wales          AUS  Australia        NaN        NaN   

         died_date     first_name  
0       1960-10-02  Jean-François  
1              NaN         Arnaud  
2       1994-07-17           Jean  
3       1978-03-20        Jacques  
4       1930-07-25         Albert  
...            ...            ...  
145495         NaN         Polina  
145496         NaN       Valeriya  
145497         NaN         Yuliya  
145498  1986-03-18          André  
145499  2003-10-20           Bill  

[145500 rows x 11 columns]

In [42]:
bios_new.query('first_name == "Keith"')

athlete_id               name   born_date     born_city  \
1897          1907       Keith Hanlon  1966-09-01           NaN   
3505          3517      Keith Wallace  1961-03-29       Preston   
6228          6255      Keith Hartley  1940-10-15     Vancouver   
8898          8946        Keith Mwila  1966-01-01           NaN   
12053        12118       Keith Hervey  1898-11-03        Fulham   
...            ...                ...         ...           ...   
99921       100722       Keith Carney  1970-02-03    Providence   
102227      103168      Keith Beavers  1983-02-09        London   
109900      111105  Keith Cumberpatch  1927-08-25  Christchurch   
115973      117348    Keith Sanderson  1975-02-02      Plymouth   
122121      124176     Keith Ferguson  1979-09-07          Sale   

             born_region born_country            NOC  height_cm  weight_kg  \
1897                 NaN          NaN        Ireland        NaN        NaN   
3505             England          GBR  Great Britain      165.0       51.0   
6228    British Columbia          CAN         Canada      200.0       85.0   
8898                 NaN          NaN         Zambia        NaN        NaN   
12053            England          GBR  Great Britain        NaN        NaN   
...                  ...          ...            ...        ...        ...   
99921       Rhode Island          USA  United States      188.0       93.0   
102227           Ontario          CAN         Canada      185.0       75.0   
109900        Canterbury          NZL    New Zealand        NaN        NaN   
115973     Massachusetts          USA  United States      183.0       95.0   
122121          Victoria          AUS      Australia      176.0       78.0   

         died_date first_name  
1897           NaN      Keith  
3505    1999-12-31      Keith  
6228           NaN      Keith  
8898    1993-01-09      Keith  
12053   1973-02-22      Keith  
...            ...        ...  
99921          NaN      Keith  
102227         NaN      Keith  
109900  2013-11-15      Keith  
115973         NaN      Keith  
122121         NaN      Keith  

[64 rows x 11 columns]

In [43]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   athlete_id    145500 non-null  int64  
 1   name          145500 non-null  object 
 2   born_date     143693 non-null  object 
 3   born_city     110908 non-null  object 
 4   born_region   110908 non-null  object 
 5   born_country  110908 non-null  object 
 6   NOC           145499 non-null  object 
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object 
 10  first_name    145500 non-null  object 
dtypes: float64(2), int64(1), object(8)
memory usage: 12.2+ MB


In [44]:
bios_new["born_datetime"] = pd.to_datetime(bios_new["born_date"], format="%Y-%m-%d")

In [45]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype         
---  ------         --------------   -----         
 0   athlete_id     145500 non-null  int64         
 1   name           145500 non-null  object        
 2   born_date      143693 non-null  object        
 3   born_city      110908 non-null  object        
 4   born_region    110908 non-null  object        
 5   born_country   110908 non-null  object        
 6   NOC            145499 non-null  object        
 7   height_cm      106651 non-null  float64       
 8   weight_kg      102070 non-null  float64       
 9   died_date      33940 non-null   object        
 10  first_name     145500 non-null  object        
 11  born_datetime  143693 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 13.3+ MB


In [46]:
bios_new["born_year"] = bios_new["born_datetime"].dt.year
bios_new[["name", "born_year"]]

name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [47]:
bios_new.to_csv("./data/bios_new.csv",index=False)

In [48]:
bios["height_category"] = bios["height_cm"].apply(lambda x: "Short" if x < 165 else ("Average" if x < 185 else "Tall"))
bios

athlete_id                   name   born_date        born_city  \
0                1  Jean-François Blanchy  1886-12-12         Bordeaux   
1                2         Arnaud Boetsch  1969-04-01           Meulan   
2                3           Jean Borotra  1898-08-13         Biarritz   
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe   
4                5           Albert Canet  1878-04-17       Wandsworth   
...            ...                    ...         ...              ...   
145495      149222      Polina Luchnikova  2002-01-30            Serov   
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)   
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas   
145498      149225         André Foussard  1899-05-19            Niort   
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill   

                 born_region born_country        NOC  height_cm  weight_kg  \
0                    Gironde          FRA     France        NaN        NaN   
1                   Yvelines          FRA     France      183.0       76.0   
2       Pyrénées-Atlantiques          FRA     France      183.0       76.0   
3                      Paris          FRA     France      168.0       64.0   
4                    England          GBR     France        NaN        NaN   
...                      ...          ...        ...        ...        ...   
145495            Sverdlovsk          RUS        ROC      167.0       61.0   
145496                Moskva          RUS        ROC      168.0       65.0   
145497           Arkhangelsk          RUS        ROC      163.0       55.0   
145498           Deux-Sèvres          FRA     France      166.0        NaN   
145499       New South Wales          AUS  Australia        NaN        NaN   

         died_date height_category  
0       1960-10-02            Tall  
1              NaN         Average  
2       1994-07-17         Average  
3       1978-03-20         Average  
4       1930-07-25            Tall  
...            ...             ...  
145495         NaN         Average  
145496         NaN         Average  
145497         NaN           Short  
145498  1986-03-18         Average  
145499  2003-10-20            Tall  

[145500 rows x 11 columns]

In [49]:
def categorize_athlete(row):
    if row["height_cm"] < 170 and row["weight_kg"] < 70:
        return "Lightweight"
    elif row["height_cm"] < 185 or row["weight_kg"] <= 80:
        return "Middleweight"
    else:
        return "Heavyweight"
    
bios["athlete_category"] = bios.apply(categorize_athlete, axis=1)
bios.head()

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   
4               England          GBR  France        NaN        NaN   

    died_date height_category athlete_category  
0  1960-10-02            Tall      Heavyweight  
1         NaN         Average     Middleweight  
2  1994-07-17         Average     Middleweight  
3  1978-03-20         Average      Lightweight  
4  1930-07-25            Tall      Heavyweight

In [50]:
nocs = pd.read_csv("./data/noc_regions.csv")
nocs.head()

NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [51]:
bios_new = pd.merge(bios, nocs, left_on="born_country", right_on="NOC", how="left")

In [52]:
bios_new.head()

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country   NOC_x  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   
4               England          GBR  France        NaN        NaN   

    died_date height_category athlete_category NOC_y  region notes  
0  1960-10-02            Tall      Heavyweight   FRA  France   NaN  
1         NaN         Average     Middleweight   FRA  France   NaN  
2  1994-07-17         Average     Middleweight   FRA  France   NaN  
3  1978-03-20         Average      Lightweight   FRA  France   NaN  
4  1930-07-25            Tall      Heavyweight   GBR      UK   NaN

In [53]:
bios_new.rename(columns={"region": "born_country_full"}, inplace=True)

In [54]:
bios_new.head()

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country   NOC_x  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   
4               England          GBR  France        NaN        NaN   

    died_date height_category athlete_category NOC_y born_country_full notes  
0  1960-10-02            Tall      Heavyweight   FRA            France   NaN  
1         NaN         Average     Middleweight   FRA            France   NaN  
2  1994-07-17         Average     Middleweight   FRA            France   NaN  
3  1978-03-20         Average      Lightweight   FRA            France   NaN  
4  1930-07-25            Tall      Heavyweight   GBR                UK   NaN

In [55]:
bios_new[bios_new["NOC_x"] != bios_new["born_country_full"]][["name", "NOC_x", "born_country_full"]]

name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [56]:
usa = bios[bios["born_country"] == "USA"].copy()
grb = bios[bios["born_country"] == "GBR"].copy()

In [57]:
new_df = pd.concat([usa, grb])

In [58]:
new_df.tail()

athlete_id                name   born_date     born_city born_region  \
144811      148512  Benjamin Alexander  1983-05-08        London     England   
144815      148517       Ashley Watson  1993-10-28  Peterborough     England   
145005      148716     Peder Kongshaug  2001-08-13     Wimbledon     England   
145319      149041          Axel Brown  1992-04-02     Harrogate     England   
145388      149111      Jean-Luc Baker  1993-10-07       Burnley     England   

       born_country                  NOC  height_cm  weight_kg died_date  \
144811          GBR              Jamaica        NaN        NaN       NaN   
144815          GBR              Jamaica        NaN        NaN       NaN   
145005          GBR               Norway      184.0       86.0       NaN   
145319          GBR  Trinidad and Tobago        NaN        NaN       NaN   
145388          GBR        United States        NaN        NaN       NaN   

       height_category athlete_category  
144811            Tall      Heavyweight  
144815            Tall      Heavyweight  
145005         Average     Middleweight  
145319            Tall      Heavyweight  
145388            Tall      Heavyweight

In [59]:
bios

athlete_id                   name   born_date        born_city  \
0                1  Jean-François Blanchy  1886-12-12         Bordeaux   
1                2         Arnaud Boetsch  1969-04-01           Meulan   
2                3           Jean Borotra  1898-08-13         Biarritz   
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe   
4                5           Albert Canet  1878-04-17       Wandsworth   
...            ...                    ...         ...              ...   
145495      149222      Polina Luchnikova  2002-01-30            Serov   
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)   
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas   
145498      149225         André Foussard  1899-05-19            Niort   
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill   

                 born_region born_country        NOC  height_cm  weight_kg  \
0                    Gironde          FRA     France        NaN        NaN   
1                   Yvelines          FRA     France      183.0       76.0   
2       Pyrénées-Atlantiques          FRA     France      183.0       76.0   
3                      Paris          FRA     France      168.0       64.0   
4                    England          GBR     France        NaN        NaN   
...                      ...          ...        ...        ...        ...   
145495            Sverdlovsk          RUS        ROC      167.0       61.0   
145496                Moskva          RUS        ROC      168.0       65.0   
145497           Arkhangelsk          RUS        ROC      163.0       55.0   
145498           Deux-Sèvres          FRA     France      166.0        NaN   
145499       New South Wales          AUS  Australia        NaN        NaN   

         died_date height_category athlete_category  
0       1960-10-02            Tall      Heavyweight  
1              NaN         Average     Middleweight  
2       1994-07-17         Average     Middleweight  
3       1978-03-20         Average      Lightweight  
4       1930-07-25            Tall      Heavyweight  
...            ...             ...              ...  
145495         NaN         Average      Lightweight  
145496         NaN         Average      Lightweight  
145497         NaN           Short      Lightweight  
145498  1986-03-18         Average     Middleweight  
145499  2003-10-20            Tall      Heavyweight  

[145500 rows x 12 columns]

In [60]:
results

year    type              discipline                          event  \
0       1912.0  Summer                  Tennis         Singles, Men (Olympic)   
1       1912.0  Summer                  Tennis         Doubles, Men (Olympic)   
2       1920.0  Summer                  Tennis         Singles, Men (Olympic)   
3       1920.0  Summer                  Tennis       Doubles, Mixed (Olympic)   
4       1920.0  Summer                  Tennis         Doubles, Men (Olympic)   
...        ...     ...                     ...                            ...   
308403  2022.0  Winter                    Luge         Singles, Men (Olympic)   
308404  2022.0  Winter  Alpine Skiing (Skiing)        Slalom, Women (Olympic)   
308405  2022.0  Winter  Alpine Skiing (Skiing)          Team, Mixed (Olympic)   
308406  2022.0  Winter  Alpine Skiing (Skiing)  Giant Slalom, Women (Olympic)   
308407  2022.0  Winter                     NaN        Slalom, Women (Olympic)   

                           as  athlete_id  noc             team  place   tied  \
0       Jean-François Blanchy           1  FRA              NaN   17.0   True   
1       Jean-François Blanchy           1  FRA   Jean Montariol    NaN  False   
2       Jean-François Blanchy           1  FRA              NaN   32.0   True   
3       Jean-François Blanchy           1  FRA  Jeanne Vaussard    8.0   True   
4       Jean-François Blanchy           1  FRA  Jacques Brugnon    4.0  False   
...                       ...         ...  ...              ...    ...    ...   
308403          Marián Skupek      148983  SVK              NaN   26.0  False   
308404          Elsa Fermbäck      148984  SWE              NaN   28.0  False   
308405          Hilma Lövblom      148985  SWE           Sweden   13.0  False   
308406          Hilma Lövblom      148985  SWE              NaN    NaN  False   
308407   Charlotta Säfvenberg      148986  NaN              NaN   24.0  False   

       medal  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN  
...      ...  
308403   NaN  
308404   NaN  
308405   NaN  
308406   NaN  
308407   NaN  

[308408 rows x 11 columns]

In [61]:
combined = pd.merge(results, bios, on="athlete_id", how="left")

In [62]:
combined.head()

year    type discipline                     event                     as  \
0  1912.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy   
1  1912.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy   
2  1920.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy   
3  1920.0  Summer     Tennis  Doubles, Mixed (Olympic)  Jean-François Blanchy   
4  1920.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy   

   athlete_id  noc             team  place   tied  ...   born_date born_city  \
0           1  FRA              NaN   17.0   True  ...  1886-12-12  Bordeaux   
1           1  FRA   Jean Montariol    NaN  False  ...  1886-12-12  Bordeaux   
2           1  FRA              NaN   32.0   True  ...  1886-12-12  Bordeaux   
3           1  FRA  Jeanne Vaussard    8.0   True  ...  1886-12-12  Bordeaux   
4           1  FRA  Jacques Brugnon    4.0  False  ...  1886-12-12  Bordeaux   

  born_region born_country     NOC height_cm weight_kg   died_date  \
0     Gironde          FRA  France       NaN       NaN  1960-10-02   
1     Gironde          FRA  France       NaN       NaN  1960-10-02   
2     Gironde          FRA  France       NaN       NaN  1960-10-02   
3     Gironde          FRA  France       NaN       NaN  1960-10-02   
4     Gironde          FRA  France       NaN       NaN  1960-10-02   

   height_category athlete_category  
0             Tall      Heavyweight  
1             Tall      Heavyweight  
2             Tall      Heavyweight  
3             Tall      Heavyweight  
4             Tall      Heavyweight  

[5 rows x 22 columns]

In [63]:
combined[["event","medal", "name"]]

event medal                   name
0              Singles, Men (Olympic)   NaN  Jean-François Blanchy
1              Doubles, Men (Olympic)   NaN  Jean-François Blanchy
2              Singles, Men (Olympic)   NaN  Jean-François Blanchy
3            Doubles, Mixed (Olympic)   NaN  Jean-François Blanchy
4              Doubles, Men (Olympic)   NaN  Jean-François Blanchy
...                               ...   ...                    ...
308403         Singles, Men (Olympic)   NaN          Marián Skupek
308404        Slalom, Women (Olympic)   NaN          Elsa Fermbäck
308405          Team, Mixed (Olympic)   NaN          Hilma Lövblom
308406  Giant Slalom, Women (Olympic)   NaN          Hilma Lövblom
308407        Slalom, Women (Olympic)   NaN   Charlotta Säfvenberg

[308408 rows x 3 columns]

In [64]:
coffee

Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          10   5.99    59.90
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [66]:
coffee.loc[[0,1], "Units Sold"] = np.nan

In [67]:
coffee

Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso         NaN   3.99    99.75
1      Monday       Latte         NaN   5.99    59.90
2     Tuesday    Espresso        30.0   3.99   119.70
3     Tuesday       Latte        20.0   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [76]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     0
price          0
revenue        0
dtype: int64

In [77]:
coffee.loc[[2,3], "Units Sold"] = np.nan
coffee.loc[[0,1], "Units Sold"] = 15

In [80]:
coffee

Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    59.90
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [81]:
coffee[coffee["Units Sold"].isna()]

Day Coffee Type  Units Sold  price  revenue
2  Tuesday    Espresso         NaN   3.99    119.7
3  Tuesday       Latte         NaN   5.99    119.8

In [82]:
coffee[coffee["Units Sold"].notna()]

Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    59.90
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [83]:
bios["born_city"].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ... 
Kirovgrad             1
Pereiaslav            1
Podgornyy             1
Kudepsta              1
Furmanov              1
Name: count, Length: 22368, dtype: int64

In [86]:
bios[bios["born_country"] == "USA"]

athlete_id               name   born_date         born_city  \
54              55      Monique Javer  1967-07-22        Burlingame   
960            964   Xóchitl Escobedo  1968-09-17       West Covina   
961            965  Angélica Gavaldón  1973-10-03         El Centro   
1231          1238     Bert Schneider  1897-07-01         Cleveland   
1345          1352         Laura Berg  1975-01-06  Santa Fe Springs   
...            ...                ...         ...               ...   
145445      149168     Kristen Santos  1994-11-02         Fairfield   
145446      149169   Corinne Stoddard  2001-08-15           Seattle   
145454      149180      Anna Hoffmann  2000-03-28           Madison   
145457      149183     Alix Wilkinson  2000-08-02     Mammoth Lakes   
145468      149195  Justin Abdelkader  1987-02-25          Muskegon   

        born_region born_country            NOC  height_cm  weight_kg  \
54       California          USA  Great Britain      177.0       64.0   
960      California          USA         Mexico      170.0       60.0   
961      California          USA         Mexico      160.0       54.0   
1231           Ohio          USA         Canada        NaN        NaN   
1345     California          USA  United States      168.0       61.0   
...             ...          ...            ...        ...        ...   
145445  Connecticut          USA  United States        NaN        NaN   
145446   Washington          USA  United States        NaN        NaN   
145454    Wisconsin          USA  United States        NaN        NaN   
145457   California          USA  United States        NaN        NaN   
145468     Michigan          USA  United States      187.0       97.0   

         died_date height_category athlete_category  
54             NaN         Average     Middleweight  
960            NaN         Average     Middleweight  
961            NaN           Short      Lightweight  
1231    1986-02-20            Tall      Heavyweight  
1345           NaN         Average      Lightweight  
...            ...             ...              ...  
145445         NaN            Tall      Heavyweight  
145446         NaN            Tall      Heavyweight  
145454         NaN            Tall      Heavyweight  
145457         NaN            Tall      Heavyweight  
145468         NaN            Tall      Heavyweight  

[9641 rows x 12 columns]

In [85]:
bios[bios["born_country"] == "USA"]["born_region"].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Massachusetts            530
Pennsylvania             530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Ke

In [87]:
coffee

Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    59.90
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [93]:
coffee.groupby(["Coffee Type"])["Units Sold"].mean()

Coffee Type
Espresso    37.500000
Latte       29.166667
Name: Units Sold, dtype: float64

In [95]:
coffee.groupby(["Coffee Type", 'Day']).agg({"Units Sold": "sum", "price": "mean"})

Units Sold  price
Coffee Type Day                         
Espresso    Friday           45.0   3.99
            Monday           15.0   3.99
            Saturday         45.0   3.99
            Sunday           45.0   3.99
            Thursday         40.0   3.99
            Tuesday           0.0   3.99
            Wednesday        35.0   3.99
Latte       Friday           35.0   5.99
            Monday           15.0   5.99
            Saturday         35.0   5.99
            Sunday           35.0   5.99
            Thursday         30.0   5.99
            Tuesday           0.0   5.99
            Wednesday        25.0   5.99

In [96]:
coffee

Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    59.90
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [97]:
pivot = coffee.pivot(columns="Coffee Type", index="Day", values="revenue")

In [98]:
pivot

Coffee Type  Espresso   Latte
Day                          
Friday         179.55  209.65
Monday          99.75   59.90
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [100]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   athlete_id        145500 non-null  int64  
 1   name              145500 non-null  object 
 2   born_date         143693 non-null  object 
 3   born_city         110908 non-null  object 
 4   born_region       110908 non-null  object 
 5   born_country      110908 non-null  object 
 6   NOC               145499 non-null  object 
 7   height_cm         106651 non-null  float64
 8   weight_kg         102070 non-null  float64
 9   died_date         33940 non-null   object 
 10  height_category   145500 non-null  object 
 11  athlete_category  145500 non-null  object 
dtypes: float64(2), int64(1), object(9)
memory usage: 13.3+ MB


In [101]:
bios["born_date"] = pd.to_datetime(bios["born_date"])

In [102]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype         
---  ------            --------------   -----         
 0   athlete_id        145500 non-null  int64         
 1   name              145500 non-null  object        
 2   born_date         143693 non-null  datetime64[ns]
 3   born_city         110908 non-null  object        
 4   born_region       110908 non-null  object        
 5   born_country      110908 non-null  object        
 6   NOC               145499 non-null  object        
 7   height_cm         106651 non-null  float64       
 8   weight_kg         102070 non-null  float64       
 9   died_date         33940 non-null   object        
 10  height_category   145500 non-null  object        
 11  athlete_category  145500 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 13.3+ MB


In [103]:
bios["month_born"] = bios["born_date"].dt.month
bios['year_born'] = bios["born_date"].dt.year
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype         
---  ------            --------------   -----         
 0   athlete_id        145500 non-null  int64         
 1   name              145500 non-null  object        
 2   born_date         143693 non-null  datetime64[ns]
 3   born_city         110908 non-null  object        
 4   born_region       110908 non-null  object        
 5   born_country      110908 non-null  object        
 6   NOC               145499 non-null  object        
 7   height_cm         106651 non-null  float64       
 8   weight_kg         102070 non-null  float64       
 9   died_date         33940 non-null   object        
 10  height_category   145500 non-null  object        
 11  athlete_category  145500 non-null  object        
 12  month_born        143693 non-null  float64       
 13  year_born         143693 non-null  float64       
dtypes: d

In [106]:
coffee["yesterday_revenue"] = coffee["revenue"].shift(2)
coffee

Day Coffee Type  Units Sold  price  revenue  yesterday_revenue
0      Monday    Espresso        15.0   3.99    99.75                NaN
1      Monday       Latte        15.0   5.99    59.90                NaN
2     Tuesday    Espresso         NaN   3.99   119.70              99.75
3     Tuesday       Latte         NaN   5.99   119.80              59.90
4   Wednesday    Espresso        35.0   3.99   139.65             119.70
5   Wednesday       Latte        25.0   5.99   149.75             119.80
6    Thursday    Espresso        40.0   3.99   159.60             139.65
7    Thursday       Latte        30.0   5.99   179.70             149.75
8      Friday    Espresso        45.0   3.99   179.55             159.60
9      Friday       Latte        35.0   5.99   209.65             179.70
10   Saturday    Espresso        45.0   3.99   179.55             179.55
11   Saturday       Latte        35.0   5.99   209.65             209.65
12     Sunday    Espresso        45.0   3.99   179.55             179.55
13     Sunday       Latte        35.0   5.99   209.65             209.65

In [108]:
coffee["pct_change"] = coffee["revenue"] / coffee["yesterday_revenue"] * 100
coffee

Day Coffee Type  Units Sold  price  revenue  yesterday_revenue  \
0      Monday    Espresso        15.0   3.99    99.75                NaN   
1      Monday       Latte        15.0   5.99    59.90                NaN   
2     Tuesday    Espresso         NaN   3.99   119.70              99.75   
3     Tuesday       Latte         NaN   5.99   119.80              59.90   
4   Wednesday    Espresso        35.0   3.99   139.65             119.70   
5   Wednesday       Latte        25.0   5.99   149.75             119.80   
6    Thursday    Espresso        40.0   3.99   159.60             139.65   
7    Thursday       Latte        30.0   5.99   179.70             149.75   
8      Friday    Espresso        45.0   3.99   179.55             159.60   
9      Friday       Latte        35.0   5.99   209.65             179.70   
10   Saturday    Espresso        45.0   3.99   179.55             179.55   
11   Saturday       Latte        35.0   5.99   209.65             209.65   
12     Sunday    Espresso        45.0   3.99   179.55             179.55   
13     Sunday       Latte        35.0   5.99   209.65             209.65   

    pct_change  
0          NaN  
1          NaN  
2   120.000000  
3   200.000000  
4   116.666667  
5   125.000000  
6   114.285714  
7   120.000000  
8   112.500000  
9   116.666667  
10  100.000000  
11  100.000000  
12  100.000000  
13  100.000000

In [110]:
bios["height_rank"] = bios["height_cm"].rank()
bios.sort_values("height_rank", ascending=False)

athlete_id                   name  born_date           born_city  \
89070        89782               Yao Ming 1980-09-12      Xuhui District   
6978          7013        Arvydas Sabonis 1964-12-19              Kaunas   
5781          5804         Tommy Burleson 1952-02-24           Crossnore   
89075        89787         Roberto Dueñas 1975-11-01              Madrid   
120266      122147           Zhang Zhaoxu 1987-11-18             Binzhou   
...            ...                    ...        ...                 ...   
145490      149217            Sin Ye-Chan 1995-06-13                 NaN   
145491      149218          Matthew Wepke 1989-12-05                 NaN   
145492      149219  Carlos García-Ordóñez 1927-04-24  La Habana (Havana)   
145493      149220     Landysh Falyakhova 1998-08-31    Dva Polya Artash   
145499      149814          Bill Phillips 1913-07-15        Dulwich Hill   

                 born_region born_country                         NOC  \
89070               Shanghai          CHN  People's Republic of China   
6978                  Kaunas          LTU      Lithuania Soviet Union   
5781          North Carolina          USA               United States   
89075                 Madrid          ESP                       Spain   
120266              Shandong          CHN  People's Republic of China   
...                      ...          ...                         ...   
145490                   NaN          NaN           Republic of Korea   
145491                   NaN          NaN                     Jamaica   
145492   Ciudad de La Habana          CUB                        Cuba   
145493  Respublika Tatarstan          RUS                         ROC   
145499       New South Wales          AUS                   Australia   

        height_cm  weight_kg   died_date height_category athlete_category  \
89070       226.0      141.0         NaN            Tall      Heavyweight   
6978        223.0      122.0         NaN            Tall      Heavyweight   
5781        223.0      102.0         NaN            Tall      Heavyweight   
89075       221.0      137.0         NaN            Tall      Heavyweight   
120266      221.0      110.0         NaN            Tall      Heavyweight   
...           ...        ...         ...             ...              ...   
145490        NaN        NaN         NaN            Tall      Heavyweight   
145491        NaN        NaN         NaN            Tall      Heavyweight   
145492        NaN        NaN  2019-11-24            Tall      Heavyweight   
145493        NaN        NaN         NaN            Tall      Heavyweight   
145499        NaN        NaN  2003-10-20            Tall      Heavyweight   

        month_born  year_born  height_rank  
89070          9.0     1980.0     106651.0  
6978          12.0     1964.0     106649.5  
5781           2.0     1952.0     106649.5  
89075         11.0     1975.0     106647.0  
120266        11.0     1987.0     106647.0  
...            ...        ...          ...  
145490         6.0     1995.0          NaN  
145491        12.0     1989.0          NaN  
145492         4.0     1927.0          NaN  
145493         8.0     1998.0          NaN  
145499         7.0     1913.0          NaN  

[145500 rows x 15 columns]